[env:esp32c5]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c5-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

; Waveshare ESP32-C5-WIFI6-KIT-N32R8-UM:
; 32 MB Quad-SPI Flash + 8 MB Quad-SPI PSRAM
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
board_build.partitions = partitions_32MB.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    bblanchon/ArduinoJson@^7.2.0
